flyingcracker/cam/urls.py
from django.urls import re_path

from . import views

app_name = 'cam'
urlpatterns = [
    re_path(r'^$', views.cam_view, name='root'),
    re_path(r'^list/$', views.cam_list, name='list'),
    re_path(r'^image/$', views.cam_image, name='image'),
]

flyingcracker/cam/models.py
from django.db import models
from localflavor.us.models import USStateField


class Category(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name_plural = "categories"


class CamManager(models.Manager):

    def belongs_to_category(self, cat=None):
        '''
        Returns a queryset of all Cams associated with specified Category.
        '''
        qs = super(type(self), self).get_query_set()
        if cat:
            qs = qs.filter(category=cat)
            return qs
        else:
            return qs


class Cam(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField()
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    state = USStateField(default="CO")
    objects = CamManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title', 'url']

flyingcracker/cam/views.py
from django.shortcuts import render

from fc3.myjson import JsonResponse

from .models import Cam, Category

CAM_CATEGORY = "cam_category"
CAM_ID = "cam_id"


def cam_view(request):
    cat_list = Category.objects.all()

    # check browser for category cookie
    category_id = request.COOKIES.get(CAM_CATEGORY, None)
    cam_id = request.COOKIES.get(CAM_ID)

    c_list, image, category = get_cam_list(category_id, cam_id)

    context = {
        'catlist': cat_list,
        'category': category,
        'camlist': c_list,
        'image': image,
    }

    agent = request.META.get('HTTP_USER_AGENT')
    if (agent and agent.find('iPhone') != -1) or 'iphone' in request.GET:
        if 'iui' in request.GET:
            return render(request, 'cam/iphone/cam.html', context)
        else:
            return render(request, 'cam/iphone/cam_initial.html', context)
    else:
        return render(request, 'cam/cam.html', context)


def cam_list(request):
    """
    Get a list of webcam images associated with a Category.

    """
    if request.is_ajax():
        cat_id = request.POST.get('cat', None)
        if cat_id:
            try:
                category = Category.objects.get(id=cat_id)
            except Category.DoesNotExist:
                c_list = Cam.objects.all()
            else:
                if category.title == "All Categories":
                    c_list = Cam.objects.all()
                else:
                    c_list = Cam.objects.belongs_to_category(cat_id)
        else:
            c_list = Cam.objects.all()

        response_dict = {}
        index = 0
        obj_dict = {}
        for obj in c_list:
            obj_dict[index] = dict({'id': obj.id, 'title': obj.title})
            index = index + 1

        obj_dict['length'] = index
        obj_dict['category'] = cat_id
        response_dict['images'] = obj_dict
        return JsonResponse(response_dict)
    else:
        return cam_view(request)


def cam_image(request):
    """
    Get a specific image URL.

    """
    if request.is_ajax() or request.GET.get('xhr'):
        try:
            id = request.POST.get('id')
            if not id:
                id = request.GET.get('id')
            image = Cam.objects.get(id=id)
        except Cam.DoesNotExist:
            image = None
            valid = False
        else:
            valid = True
        return JsonResponse({'image': image, 'valid': valid})
    else:
        return cam_view(request)


def get_cam_list(cat_id, cam_id=None):
    """
    Returns a list of images, a "default" image,
    and the category these images are in.
    """
    # Set the image first
    if cam_id:
        try:
            image = Cam.objects.get(id=cam_id)
        except Cam.DoesNotExist:
            image = None
    else:
        image = None

    if cat_id:
        try:
            category = Category.objects.get(id=cat_id)
        except Category.DoesNotExist:
            c_list = Cam.objects.all()
            category = get_default_category()
        else:
            if category.title == "All Categories":
                c_list = Cam.objects.all()
            else:
                c_list = Cam.objects.filter(category=category)
                # if we don't already have an image,
                # or the image doesn't appear in the specified category
                # set the image to the first one in the category
                if not image or image not in c_list:
                    image = c_list[0]
    else:
        c_list = Cam.objects.all()
        category = get_default_category()

    if not image:
        image = get_default_image()

    return c_list, image, category


def get_default_image():
    try:
        image = Cam.objects.get(title__contains="Whetstone")
    except Cam.DoesNotExist:
        image = None
    return image


def get_default_category():
    return Category.objects.get(title="All Categories")

flyingcracker/cam/templates/cam/cam.html
{% extends "webcam.html" %}

{% block body %}
    {% include "cam/cam_select.html" %}
    <div id="bd">
        {% include "cam/cam_snippet.html" %}
    </div>
{% endblock body %}

flyingcracker/cam/templates/cam/cam_select.html
<div id="hd">
    <div class="select-bar">
        <div class="yui-g">
            <div class="yui-u first" id="image-select">
                <form action="." method="post">{% csrf_token %}
                    <select id="id-image" class="selectLink">
                        <option value="">--Select webcam--</option>
                        {% for cam in camlist %}
                        <option value="{{ cam.id }}"{% ifequal cam.id image.id %} selected="selected"{% endifequal %}>
                            {{ cam.title }}
                        </option>
                        {% endfor %}
                    </select>
                </form>
            </div>

            <div class="yui-u" id="category-select">
                <form action="." method="post">{% csrf_token %}
                    <select id="id-category" class="selectLink">
                        <option value="">--Select category--</option>
                        {% for cat in catlist %}
                        <option value="{{ cat.id }}"{% ifequal cat category %} selected="selected"{% endifequal %}>
                            {{ cat.title }}
                        </option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

function loadSelect(type, args) {
    var t = args[0];
    // do something here, like figure out if this is the category select or image select
    if (t.id === 'id-category') {
        webcam.request_list(t);
    } else if (t.id === 'id-image') {
        webcam.request_image(t);
    } else {
        alert('unknown select');
    }

    // onchange=reDir(this.options[this.selectedIndex].value);
};

selectChange = new YAHOO.util.CustomEvent('select change');
selectChange.subscribe(loadSelect);

function initSelects() {
    YAHOO.util.Event.addListener(this, "change", newSelect);
};

function newSelect(e) {
    var t = YAHOO.util.Event.getTarget(e);

    if (t.selectedIndex != 0) {
        selectChange.fire(t);
        YAHOO.util.Event.preventDefault(e);
    }
};

YAHOO.util.Event.onAvailable('id-category', initSelects);
YAHOO.util.Event.onAvailable('id-image', initSelects);


var webcam = {

    request_list: function(select) {
        // POST a request for new data
        var post_url = '{% url 'cam:list' %}';
        var post_data = 'cat=' + select.value + '&csrfmiddlewaretoken=' + YAHOO.util.Cookie.get("csrftoken");
        var cObj = YAHOO.util.Connect.asyncRequest('POST', post_url, webcam.request_list_callback, post_data);
        Set_Cookie("cam_category", ''+select.value, 7, '/', '', '');
    },

    request_list_callback: {
        success: function(o) {
            // This turns the JSON string into a JavaScript object.
            try {
                var response_obj = YAHOO.lang.JSON.parse(o.responseText);
            }
            catch (e) {
                alert("Invalid server response in webcam.js ["+o.responseText+"], please inform CracklyFinger")
            }

			var image_select = document.getElementById('id-image');
            // remove existing options
            image_select.options.length = 0;
            // Add the image ids
            webcam.add_option(image_select.options, 0, '--Select webcam--')
            objs = response_obj.images;
            for (var i=0; i<objs.length; i++) {
                webcam.add_option(image_select.options, objs[i].id, objs[i].title)
            }
        },

        failure: function(o) {
            var a = 1; // alert('An error has occurred');
        }

    },

    request_image: function(select) {
        // POST a request for new data
        var post_url = '{% url 'cam:image' %}';
        var post_data = 'id=' + select.value + '&csrfmiddlewaretoken=' + YAHOO.util.Cookie.get("csrftoken");
        var cObj = YAHOO.util.Connect.asyncRequest('POST', post_url, webcam.request_image_callback, post_data);
        Set_Cookie("cam_id", ''+select.value, 7, '/', '', '');
    },

    request_image_callback: {
        success: function(o) {
            // This turns the JSON string into a JavaScript object.
            try {
                var response_obj = YAHOO.lang.JSON.parse(o.responseText);
                var image = response_obj.image;
            }
            catch (e) {
                alert("Invalid server response in webcam.js ["+o.responseText+"], please inform CracklyFinger")
            }
            if (response_obj.valid) {
                var el = document.getElementById('cam-image');
                el.alt = image.title;
                el.src = image.url;
                el = document.getElementById('cam-description');
                el.innerHTML = image.title;
            }
        },

        failure: function(o) {
            var a = 1; // alert('An error has occurred');
        }

    },

    add_option: function(sel,id,title) {
        var newElem = document.createElement("option");
        newElem.text = title;
        newElem.value = id;
        sel.add(newElem)
    }
};

</script>

flyingcracker/cam/templates/cam/cam_snippet.html
<div id="webcam">
    <img id="cam-image" alt="{{ image.title }}" src="{{ image.url }}" />

    <div id="cam-description">
        <p>{% firstof image.description image.title "webcam" %}</p>
        <br />
        <p>[Note: Your webcam selection is "sticky", so that next time you visit this site you will see the same webcam you last selected.
        We do this with "cookies" so if you have them disabled in your browser this behavior will not occur.]</p>
    </div>
</div>

flyingcracker/cam/templates/cam/suggest.html

<style>

label {float:left;text-align:right;width:30%;padding-right:5px; }
</style>

<script language="javascript">
YAHOO.namespace("suggest_cam");

function init() {
	
	// Define various event handlers for Dialog
	var handleSubmit = function() {
		this.submit();
	};
	var handleCancel = function() {
		this.cancel();
	};
	var handleSuccess = function(o) {
		alert("Thanks for your submission");
	};
	var handleFailure = function(o) {
		alert("Submission failed: " + o.status);
	};

	// Instantiate the Dialog
	YAHOO.suggest_cam.dialog1 = new YAHOO.widget.Dialog("dialog1", 
                                                        { width : "300px",
                                                          fixedcenter : false,
                                                          visible : false,
                                                          draggable : false,
                                                          constraintoviewport : true,
                                                          buttons : [ { text:"Submit", handler:handleSubmit, isDefault:true },
                                                                      { text:"Cancel", handler:handleCancel } ]
                                                         } );
	
	// Validate the entries in the form to require the URL.
	YAHOO.suggest_cam.dialog1.validate = function() {
		var data = this.getData();
		if (data.url == "") {
			alert("Please enter a URL (web address) for the webcam.");
			return false;
		} else {
			return true;
		}
	};

	// Wire up the success and failure handlers
	YAHOO.suggest_cam.dialog1.callback = { success: handleSuccess,
										 failure: handleFailure };
	
	// Render the Dialog
	YAHOO.suggest_cam.dialog1.render();

	YAHOO.util.Event.addListener("suggest", "click", YAHOO.suggest_cam.dialog1.show, YAHOO.suggest_cam.dialog1, true);
}

YAHOO.util.Event.onDOMReady(init);
</script>

<br />
<div>
    <button id="suggest">Suggest Cam</button> 
</div>

<div id="dialog1">
    <div class="hd">Suggest a webcam</div>
    <div class="bd">
        <form method="POST" action="/cam/suggest/">{% csrf_token %}
            <label for="url">URL address:</label><input type="textbox" name="url" />
            <label for="description">Description:</label><textarea id="id_description" name="description" rows="2" cols="40"></textarea>
        </form>
    </div>
</div>
